### PR TITLE
added scroll and scan in elastic search

### PR DESCRIPTION
**Pull request by krishnaramya**
This is just for peer review only. I will update documentation and separate scroll function in soon.
peer review

### CODE REVIEW

**Comment by hop-along-polly** [comment]
We also need to be returning the _id field so the individual get function will work. You can do that in this PR or a separate one....your choice.

**Comment by krishnaramya** [comment]
added that change with the different commit message in this same pull request.

**Comment by krishnaramya** [comment]
I have updated documentation.

**Comment by hop-along-polly** [comment]
I put in PR#59 which finished this off with unit tests.

**Pull request merged**
